# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mrvak\Desktop\design\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent
from PyQt5.Qt import QAbstractItemView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 778)
        MainWindow.setMinimumSize(QtCore.QSize(600, 500))
        font = QtGui.QFont()
        font.setFamily("\"Franklin Gothic Demi Cond\"")
        font.setPointSize(-1)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget {\n"
"    background: #1D1B26;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    font-family: \\\"Franklin Gothic Demi Cond\\\";\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("QTabBar::tab:selected {\n"
"    color: white;\n"
"    background-color: #1D1B26;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    color: rgb(136, 143, 147);\n"
"    background-color: rgb(43, 43, 43);\n"
"    border-bottom-color: rgb(85, 85, 127);\n"
"}\n"
"\n"
"QTabWidget:pane { /*replace icon text as pane ok....*/\n"
"    margin: 1px,0px,0px,0px;\n"
"    border-top: 2px solid rgb(85, 85, 127);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border: 2px solid rgb(85, 85, 127);\n"
"    border-bottom-color: rgb(255,255,255, 0);\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    padding: 5px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"    font-size: 16px;\n"
"    width: 80px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    bottom: -3px;\n"
"    background-color: rgb(255,255,255);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.steam_login_group = QtWidgets.QGroupBox(self.tab_1)
        self.steam_login_group.setEnabled(True)
        self.steam_login_group.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"    margin: 0px;\n"
"}")
        self.steam_login_group.setTitle("")
        self.steam_login_group.setFlat(False)
        self.steam_login_group.setCheckable(False)
        self.steam_login_group.setObjectName("steam_login_group")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.steam_login_group)
        self.verticalLayout_5.setContentsMargins(15, 0, 15, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(10, 30, 10, 0)
        self.horizontalLayout_10.setSpacing(20)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.login_label = QtWidgets.QLabel(self.steam_login_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_label.sizePolicy().hasHeightForWidth())
        self.login_label.setSizePolicy(sizePolicy)
        self.login_label.setMinimumSize(QtCore.QSize(50, 0))
        self.login_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("\"Franklin Gothic Demi Cond\"")
        font.setPointSize(-1)
        self.login_label.setFont(font)
        self.login_label.setStyleSheet("QWidget {\n"
"    background-color: transparent;\n"
"    color: rgb(136, 143, 147);\n"
"    border: none;\n"
"    font-size: 22px;\n"
"}")
        self.login_label.setObjectName("login_label")
        self.horizontalLayout_10.addWidget(self.login_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_11.setSpacing(20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(10, 0, 10, 20)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.account_name_label = QtWidgets.QLabel(self.steam_login_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_name_label.sizePolicy().hasHeightForWidth())
        self.account_name_label.setSizePolicy(sizePolicy)
        self.account_name_label.setMinimumSize(QtCore.QSize(165, 30))
        self.account_name_label.setMaximumSize(QtCore.QSize(165, 30))
        font = QtGui.QFont()
        font.setFamily("\"Franklin Gothic Demi Cond\"")
        font.setPointSize(-1)
        self.account_name_label.setFont(font)
        self.account_name_label.setStyleSheet("QWidget {\n"
"    background: rgb(46, 46, 46);\n"
"    color: rgb(255, 182, 155);\n"
"    font-size: 16px;\n"
"    padding: 4px;\n"
"}")
        self.account_name_label.setObjectName("account_name_label")
        self.verticalLayout_6.addWidget(self.account_name_label)
        self.account_name_input = QtWidgets.QLineEdit(self.steam_login_group)
        self.account_name_input.setMinimumSize(QtCore.QSize(300, 0))
        self.account_name_input.setMaximumSize(QtCore.QSize(300, 16777215))
        self.account_name_input.setStyleSheet("QWidget {\n"
"    padding: 4px;\n"
"    border: 2px solid rgb(60, 63, 65);\n"
"}")
        self.account_name_input.setObjectName("account_name_input")
        self.verticalLayout_6.addWidget(self.account_name_input)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_13.setSpacing(20)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(10, 0, 10, 20)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.account_pass_label = QtWidgets.QLabel(self.steam_login_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_pass_label.sizePolicy().hasHeightForWidth())
        self.account_pass_label.setSizePolicy(sizePolicy)
        self.account_pass_label.setMinimumSize(QtCore.QSize(165, 30))
        self.account_pass_label.setMaximumSize(QtCore.QSize(165, 30))
        font = QtGui.QFont()
        font.setFamily("\"Franklin Gothic Demi Cond\"")
        font.setPointSize(-1)
        self.account_pass_label.setFont(font)
        self.account_pass_label.setStyleSheet("QWidget {\n"
"    background: rgb(46, 46, 46);\n"
"    color: rgb(255, 182, 155);\n"
"    font-size: 16px;\n"
"    padding: 4px;\n"
"}")
        self.account_pass_label.setObjectName("account_pass_label")
        self.verticalLayout_7.addWidget(self.account_pass_label)
        self.account_pass_input = QtWidgets.QLineEdit(self.steam_login_group)
        self.account_pass_input.setMinimumSize(QtCore.QSize(300, 0))
        self.account_pass_input.setMaximumSize(QtCore.QSize(300, 16777215))
        self.account_pass_input.setStyleSheet("QWidget {\n"
"    padding: 4px;\n"
"    border: 2px solid rgb(60, 63, 65);\n"
"}")
        self.account_pass_input.setObjectName("account_pass_input")
        self.verticalLayout_7.addWidget(self.account_pass_input)
        self.horizontalLayout_13.addLayout(self.verticalLayout_7)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_14.setSpacing(20)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.login_button = QtWidgets.QPushButton(self.steam_login_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_button.sizePolicy().hasHeightForWidth())
        self.login_button.setSizePolicy(sizePolicy)
        self.login_button.setMinimumSize(QtCore.QSize(150, 30))
        self.login_button.setStyleSheet("QWidget {\n"
"    background-color: rgb(70, 70, 130);\n"
"    font-size: 22px;\n"
"}")
        self.login_button.setObjectName("login_button")
        self.horizontalLayout_14.addWidget(self.login_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.verticalLayout_4.addWidget(self.steam_login_group)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.login_loading_label = QtWidgets.QLabel(self.tab_1)
        self.login_loading_label.setMaximumSize(QtCore.QSize(205, 16777215))
        self.login_loading_label.setStyleSheet("QWidget {\n"
"    background-color: transparent;\n"
"    color: rgb(136, 143, 147);\n"
"    border: none;\n"
"    font-size: 22px;\n"
"}")
        self.login_loading_label.setObjectName("login_loading_label")
        self.horizontalLayout_8.addWidget(self.login_loading_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.already_logined_group = QtWidgets.QGroupBox(self.tab_1)
        self.already_logined_group.setEnabled(True)
        self.already_logined_group.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"    margin: 0px;\n"
"}")
        self.already_logined_group.setTitle("")
        self.already_logined_group.setFlat(False)
        self.already_logined_group.setCheckable(False)
        self.already_logined_group.setObjectName("already_logined_group")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.already_logined_group)
        self.verticalLayout_16.setContentsMargins(15, 0, 15, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(10, 30, 10, 0)
        self.horizontalLayout_24.setSpacing(20)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem8)
        self.login_success_label = QtWidgets.QLabel(self.already_logined_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_success_label.sizePolicy().hasHeightForWidth())
        self.login_success_label.setSizePolicy(sizePolicy)
        self.login_success_label.setMinimumSize(QtCore.QSize(230, 0))
        self.login_success_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("\"Franklin Gothic Demi Cond\"")
        font.setPointSize(-1)
        self.login_success_label.setFont(font)
        self.login_success_label.setStyleSheet("QWidget {\n"
"    background-color: transparent;\n"
"    color: rgb(164, 197, 161);\n"
"    border: none;\n"
"    font-size: 22px;\n"
"}")
        self.login_success_label.setObjectName("login_success_label")
        self.horizontalLayout_24.addWidget(self.login_success_label)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem9)
        self.verticalLayout_16.addLayout(self.horizontalLayout_24)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_16.addItem(spacerItem10)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_25.setSpacing(20)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem11)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setContentsMargins(10, 0, 10, 20)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.logined_account_name_label = QtWidgets.QLabel(self.already_logined_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logined_account_name_label.sizePolicy().hasHeightForWidth())
        self.logined_account_name_label.setSizePolicy(sizePolicy)
        self.logined_account_name_label.setMinimumSize(QtCore.QSize(165, 30))
        self.logined_account_name_label.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("\"Franklin Gothic Demi Cond\"")
        font.setPointSize(-1)
        self.logined_account_name_label.setFont(font)
        self.logined_account_name_label.setStyleSheet("QWidget {\n"
"    background: rgb(46, 46, 46);\n"
"    color: rgb(255, 182, 155);\n"
"    font-size: 16px;\n"
"    padding: 4px;\n"
"}")
        self.logined_account_name_label.setObjectName("logined_account_name_label")
        self.verticalLayout_17.addWidget(self.logined_account_name_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame = QtWidgets.QFrame(self.already_logined_group)
        self.frame.setMinimumSize(QtCore.QSize(150, 150))
        self.frame.setStyleSheet("QFrame {\n"
"    border-image: url(\"C:/Users/mrvak/Pictures/Saved Pictures/uchiha_drip.jpg\") 0 0 0 0 stretch stretch;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_17.addWidget(self.frame)
        self.horizontalLayout_25.addLayout(self.verticalLayout_17)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem12)
        self.verticalLayout_16.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_26.setSpacing(20)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.logout_button = QtWidgets.QPushButton(self.already_logined_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logout_button.sizePolicy().hasHeightForWidth())
        self.logout_button.setSizePolicy(sizePolicy)
        self.logout_button.setMinimumSize(QtCore.QSize(150, 30))
        self.logout_button.setStyleSheet("QWidget {\n"
"    background-color: rgb(70, 70, 130);\n"
"    font-size: 22px;\n"
"}")
        self.logout_button.setObjectName("logout_button")
        self.horizontalLayout_26.addWidget(self.logout_button)
        self.verticalLayout_16.addLayout(self.horizontalLayout_26)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem13)
        self.verticalLayout_4.addWidget(self.already_logined_group)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_4.setContentsMargins(20, 20, 20, 0)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.url_label = QtWidgets.QLabel(self.tab_2)
        self.url_label.setStyleSheet("QWidget {\n"
"    background: rgb(46, 46, 46);\n"
"    color: rgb(255, 182, 155);\n"
"    font-size: 16px;\n"
"    padding: 4px;\n"
"}")
        self.url_label.setObjectName("url_label")
        self.horizontalLayout_12.addWidget(self.url_label)
        self.url_input = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_input.sizePolicy().hasHeightForWidth())
        self.url_input.setSizePolicy(sizePolicy)
        self.url_input.setMinimumSize(QtCore.QSize(150, 25))
        self.url_input.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("\"Franklin Gothic Demi Cond\"")
        font.setPointSize(-1)
        self.url_input.setFont(font)
        self.url_input.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(60, 63, 65);\n"
"}")
        self.url_input.setText("")
        self.url_input.setObjectName("url_input")
        self.horizontalLayout_12.addWidget(self.url_input)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.price_label = QtWidgets.QLabel(self.tab_2)
        self.price_label.setMinimumSize(QtCore.QSize(50, 0))
        self.price_label.setStyleSheet("QWidget {\n"
"    background: rgb(46, 46, 46);\n"
"    color: rgb(255, 182, 155);\n"
"    font-size: 16px;\n"
"    padding: 4px;\n"
"}")
        self.price_label.setObjectName("price_label")
        self.horizontalLayout_2.addWidget(self.price_label)
        self.price_input = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.price_input.setMinimumSize(QtCore.QSize(70, 0))
        self.price_input.setMaximumSize(QtCore.QSize(70, 16777215))
        self.price_input.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(60, 63, 65);\n"
"    padding: 2px;\n"
"}")
        self.price_input.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.price_input.setMaximum(100000.99)
        self.price_input.setObjectName("price_input")
        self.horizontalLayout_2.addWidget(self.price_input)
        self.price_label_2 = QtWidgets.QLabel(self.tab_2)
        self.price_label_2.setMinimumSize(QtCore.QSize(30, 0))
        self.price_label_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.price_label_2.setStyleSheet("QWidget {\n"
"    background: rgb(46, 46, 46);\n"
"    color: rgb(255, 182, 155);\n"
"    font-size: 16px;\n"
"    padding: 4px;\n"
"}")
        self.price_label_2.setObjectName("price_label_2")
        self.horizontalLayout_2.addWidget(self.price_label_2)
        self.price_input_2 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.price_input_2.setMinimumSize(QtCore.QSize(70, 0))
        self.price_input_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.price_input_2.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(60, 63, 65);\n"
"    padding: 2px;\n"
"}")
        self.price_input_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.price_input_2.setMaximum(100000.99)
        self.price_input_2.setObjectName("price_input_2")
        self.horizontalLayout_2.addWidget(self.price_input_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.float_value_label = QtWidgets.QLabel(self.tab_2)
        self.float_value_label.setStyleSheet("QWidget {\n"
"    background: rgb(46, 46, 46);\n"
"    color: rgb(255, 182, 155);\n"
"    font-size: 16px;\n"
"    padding: 4px;\n"
"}")
        self.float_value_label.setObjectName("float_value_label")
        self.horizontalLayout_3.addWidget(self.float_value_label)
        self.float_value_input = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.float_value_input.setMinimumSize(QtCore.QSize(70, 0))
        self.float_value_input.setMaximumSize(QtCore.QSize(70, 16777215))
        self.float_value_input.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(60, 63, 65);\n"
"    padding: 2px;\n"
"}")
        self.float_value_input.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.float_value_input.setMaximum(100000.99)
        self.float_value_input.setDecimals(5)
        self.float_value_input.setObjectName("float_value_input")
        self.horizontalLayout_3.addWidget(self.float_value_input)
        self.float_value_label_2 = QtWidgets.QLabel(self.tab_2)
        self.float_value_label_2.setMinimumSize(QtCore.QSize(30, 0))
        self.float_value_label_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.float_value_label_2.setStyleSheet("QWidget {\n"
"    background: rgb(46, 46, 46);\n"
"    color: rgb(255, 182, 155);\n"
"    font-size: 16px;\n"
"    padding: 4px;\n"
"}")
        self.float_value_label_2.setObjectName("float_value_label_2")
        self.horizontalLayout_3.addWidget(self.float_value_label_2)
        self.float_value_input_2 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.float_value_input_2.setMinimumSize(QtCore.QSize(70, 0))
        self.float_value_input_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.float_value_input_2.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(60, 63, 65);\n"
"    padding: 2px;\n"
"}")
        self.float_value_input_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.float_value_input_2.setMaximum(100000.99)
        self.float_value_input_2.setDecimals(5)
        self.float_value_input_2.setObjectName("float_value_input_2")
        self.horizontalLayout_3.addWidget(self.float_value_input_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.paint_seed_label = QtWidgets.QLabel(self.tab_2)
        self.paint_seed_label.setStyleSheet("QWidget {\n"
"    background: rgb(46, 46, 46);\n"
"    color: rgb(255, 182, 155);\n"
"    font-size: 16px;\n"
"    padding: 4px;\n"
"}")
        self.paint_seed_label.setObjectName("paint_seed_label")
        self.horizontalLayout_9.addWidget(self.paint_seed_label)
        self.paint_seed_input = QtWidgets.QSpinBox(self.tab_2)
        self.paint_seed_input.setMinimumSize(QtCore.QSize(70, 0))
        self.paint_seed_input.setMaximumSize(QtCore.QSize(70, 16777215))
        self.paint_seed_input.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(60, 63, 65);\n"
"    padding: 2px;\n"
"}")
        self.paint_seed_input.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.paint_seed_input.setMaximum(100000)
        self.paint_seed_input.setObjectName("paint_seed_input")
        self.horizontalLayout_9.addWidget(self.paint_seed_input)
        self.paint_seed_label_2 = QtWidgets.QLabel(self.tab_2)
        self.paint_seed_label_2.setMinimumSize(QtCore.QSize(30, 0))
        self.paint_seed_label_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.paint_seed_label_2.setStyleSheet("QWidget {\n"
"    background: rgb(46, 46, 46);\n"
"    color: rgb(255, 182, 155);\n"
"    font-size: 16px;\n"
"    padding: 4px;\n"
"}")
        self.paint_seed_label_2.setObjectName("paint_seed_label_2")
        self.horizontalLayout_9.addWidget(self.paint_seed_label_2)
        self.paint_seed_input_2 = QtWidgets.QSpinBox(self.tab_2)
        self.paint_seed_input_2.setMinimumSize(QtCore.QSize(70, 0))
        self.paint_seed_input_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.paint_seed_input_2.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(60, 63, 65);\n"
"    padding: 2px;\n"
"}")
        self.paint_seed_input_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.paint_seed_input_2.setMaximum(100000)
        self.paint_seed_input_2.setObjectName("paint_seed_input_2")
        self.horizontalLayout_9.addWidget(self.paint_seed_input_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_9)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(20, 20, 20, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(0, 0, 20, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem15)
        self.empty_label = QtWidgets.QLabel(self.tab_2)
        self.empty_label.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("\"Franklin Gothic Demi Cond\"")
        font.setPointSize(-1)
        self.empty_label.setFont(font)
        self.empty_label.setStyleSheet("QWidget {\n"
"    border: none;\n"
"    background: transparent;\n"
"    color: rgb(136, 143, 147);\n"
"    font-size: 18px;\n"
"    padding: auto;\n"
"    padding-top: 0px;\n"
"    padding-bottom: 0px;\n"
"}")
        self.empty_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.empty_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.empty_label.setLineWidth(3)
        self.empty_label.setText("")
        self.empty_label.setObjectName("empty_label")
        self.horizontalLayout_17.addWidget(self.empty_label)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem16)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.thread_name_label = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thread_name_label.sizePolicy().hasHeightForWidth())
        self.thread_name_label.setSizePolicy(sizePolicy)
        self.thread_name_label.setMinimumSize(QtCore.QSize(50, 30))
        self.thread_name_label.setStyleSheet("QWidget {\n"
"    background: rgb(46, 46, 46);\n"
"    color: rgb(255, 182, 155);\n"
"    font-size: 16px;\n"
"    padding: 4px;\n"
"}")
        self.thread_name_label.setObjectName("thread_name_label")
        self.horizontalLayout_7.addWidget(self.thread_name_label)
        self.thread_name_input = QtWidgets.QLineEdit(self.tab_2)
        self.thread_name_input.setMinimumSize(QtCore.QSize(150, 30))
        self.thread_name_input.setMaximumSize(QtCore.QSize(150, 16777215))
        self.thread_name_input.setStyleSheet("QWidget {\n"
"    padding: 2px;\n"
"    border: 2px solid rgb(60, 63, 65);\n"
"}")
        self.thread_name_input.setObjectName("thread_name_input")
        self.horizontalLayout_7.addWidget(self.thread_name_input)
        self.run_bot_button = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_bot_button.sizePolicy().hasHeightForWidth())
        self.run_bot_button.setSizePolicy(sizePolicy)
        self.run_bot_button.setMinimumSize(QtCore.QSize(150, 30))
        self.run_bot_button.setStyleSheet("QWidget {\n"
"    background-color: rgb(70, 70, 130);\n"
"    font-size: 16px;\n"
"    padding-bottom: 3px;\n"
"    margin-left: 20px;\n"
"}")
        self.run_bot_button.setObjectName("run_bot_button")
        self.horizontalLayout_7.addWidget(self.run_bot_button)
        spacerItem17 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem18)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem19)
        self.threads_label = QtWidgets.QLabel(self.tab_2)
        self.threads_label.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("\"Franklin Gothic Demi Cond\"")
        font.setPointSize(-1)
        self.threads_label.setFont(font)
        self.threads_label.setStyleSheet("QWidget {\n"
"    border: none;\n"
"    background: transparent;\n"
"    color: rgb(136, 143, 147);\n"
"    font-size: 18px;\n"
"    padding: auto;\n"
"    padding-top: 0px;\n"
"    padding-bottom: 0px;\n"
"}")
        self.threads_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.threads_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.threads_label.setLineWidth(3)
        self.threads_label.setObjectName("threads_label")
        self.horizontalLayout_16.addWidget(self.threads_label)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.listWidget = QtWidgets.QListWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 20, 20, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem21)
        self.items_label = QtWidgets.QLabel(self.tab_2)
        self.items_label.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("\"Franklin Gothic Demi Cond\"")
        font.setPointSize(-1)
        self.items_label.setFont(font)
        self.items_label.setStyleSheet("QWidget {\n"
"    border: none;\n"
"    background: transparent;\n"
"    color: rgb(136, 143, 147);\n"
"    font-size: 18px;\n"
"    padding: auto;\n"
"    padding-top: 0px;\n"
"    padding-bottom: 0px;\n"
"}")
        self.items_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.items_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.items_label.setLineWidth(3)
        self.items_label.setObjectName("items_label")
        self.horizontalLayout_5.addWidget(self.items_label)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem22)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    color: rgb(136, 143, 147);\n"
"    background-color: #2C2A37;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #2C2A37;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)

        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.setStretch(2, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_10.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_label.setText(_translate("MainWindow", "Вход"))
        self.account_name_label.setText(_translate("MainWindow", "Имя аккаунта Steam"))
        self.account_pass_label.setText(_translate("MainWindow", "Пароль"))
        self.login_button.setText(_translate("MainWindow", "Войти"))
        self.login_loading_label.setText(_translate("MainWindow", "Производится вход"))
        self.login_success_label.setText(_translate("MainWindow", "Авторизация успешна"))
        self.logined_account_name_label.setText(_translate("MainWindow", "account_name"))
        self.logout_button.setText(_translate("MainWindow", "Выйти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Вход"))
        self.url_label.setText(_translate("MainWindow", "URL"))
        self.price_label.setText(_translate("MainWindow", "Цена"))
        self.price_label_2.setText(_translate("MainWindow", "до"))
        self.float_value_label.setText(_translate("MainWindow", "Float value"))
        self.float_value_label_2.setText(_translate("MainWindow", "до"))
        self.paint_seed_label.setText(_translate("MainWindow", "Paint seed"))
        self.paint_seed_label_2.setText(_translate("MainWindow", "до"))
        self.thread_name_label.setText(_translate("MainWindow", "Название потока"))
        self.run_bot_button.setText(_translate("MainWindow", "Запустить бота"))
        self.threads_label.setText(_translate("MainWindow", "Потоки"))
        self.items_label.setText(_translate("MainWindow", "Предметы"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Цена"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Float"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Paint seed"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "url"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "thread"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "js"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Главная"))
